data:
  image: kishor05/orodata-master
source_code:
  image: kishor05/orocrm-master
  volumes:
    - ./../aakroncrm-master/app/config:/var/www/app/config
    - ./../aakroncrm-master/app/AppKernel.php:/var/www/app/AppKernel.php
    - ./../aakroncrm-master/src:/var/www/src
    - ./../aakroncrm-master/composer.json:/var/www/composer.json
db:
  image: mysql:5.5
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=orocrm
    - MYSQL_USER=orocrm
    - MYSQL_PASSWORD=orocrm
  volumes_from:
    - data
  volumes:
    - ./../mysql:/var/lib/mysql
mail:
  image: catatnight/postfix
  expose:
    - "25"
  environment:
    - maildomain=localhost
    - smtp_user=user@localhost:password
minion:
  image: kishor05/oromono-master
  links:
    - "db"
    - "mail"
  ports:
    - "3080:80"
    - "3088:8080"
  volumes_from:
    - data
    - source_code
  environment:
    - CMD_INIT_BEFORE=
    - CMD_INIT_CLEAN=runuser -s /bin/sh -c '/usr/bin/php /var/www/app/console oro:install --timeout 3600 --force --drop-database --env=prod --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="123456" --user-email="kparmar@officebrain.com" --organization-name="Aakron CRM" --application-url="http://oro.loc/"' www-data
    - CMD_INIT_INSTALLED=
    - CMD_INIT_AFTER=
    - APP_DB_DRIVER=pdo_mysql
    - APP_DB_HOST=db
    - APP_DB_PORT=3306
    - APP_DB_USER=orocrm
    - APP_DB_PASSWORD=orocrm
    - APP_DB_NAME=orocrm
    - APP_HOSTNAME=localhost
    - APP_MAILER_TRANSPORT=smtp
    - APP_MAILER_HOST=mail
    - APP_MAILER_PORT=25
    - APP_MAILER_ENCRYPTION=
    - APP_MAILER_USER=user
    - APP_MAILER_PASSWORD=password
    - APP_WEBSOCKET_BACKEND_PORT=8080  
    - APP_WEBSOCKET_FRONTEND_PORT=3088  
    - APP_SECRET=123456789  
    - APP_IS_INSTALLED=
